"""Initial

Revision ID: df904ea5530e
Revises: 3c9428c28b53
Create Date: 2025-11-04 16:55:02.237952

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "df904ea5530e"
down_revision: Union[str, Sequence[str], None] = "3c9428c28b53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
