"""Initial

Revision ID: 670c4804ff8a
Revises: bdc536c01309
Create Date: 2025-11-04 16:54:53.465336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "670c4804ff8a"
down_revision: Union[str, Sequence[str], None] = "bdc536c01309"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_id"), "auth", ["id"], unique=False)
    op.create_index(op.f("ix_auth_login"), "auth", ["login"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_login"), table_name="auth")
    op.drop_index(op.f("ix_auth_id"), table_name="auth")
    op.drop_table("auth")
    # ### end Alembic commands ###
