"""Initial

Revision ID: bdc536c01309
Revises:
Create Date: 2025-11-04 16:49:36.073641

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bdc536c01309"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
